### ISSUE TITLE
Sentinel value to ensure early correctness

### ISSUE THREAD

**Issue by Ginden** [node-config/node-config#592]
### I'm submitting a ... 
  - [  ] bug report
  - [ x ] feature request

### Use case

We keep general configuration in repository and passwords/credentials in local.js files located on server.

So, currently our `config/default.js` file looks like:
```
module.exports = {
  db: {
    host: 'foobar.local',
    user: 'our_user'
    password: null,
  }
}
```
And `config/local.js` on server looks like:
```
module.exports = {
  db: {
    password: 'some password'
  }
}
```

I would like to propose special sentinel value. With use like:
```
const sentinel = require('config').util.sentinel;
module.exports = {
   db: {
      password: sentinel,
   }
}
```

Sentinel can never appear in resulting config, resulting in early error - therefore forcing users to write proper value in child config.

**Comment by markstos** [comment]
This is an interesting idea.  I have been using `undefined` in the main config, and then the app will crash if it expects a defined value there. 

The difference with my approach is that I don't find out about the error until `run time`, which could be sometime later if the feature is not popular and the code path is not frequently used. 

You are proposing than error be thrown at application `boot` time instead. Because the feedback is provided sooner the problem can be detected and fixed faster.

I have a couple thoughts here.

First, there is some discussion about a next-gen architecture of `node-config` which could "validators" and "middleware" so extra validation steps like this could be applied.  Search here: https://github.com/lorenwest/node-config/issues/569  For "Parser.validators" and "Parser.middleware".

Perhaps we should take a broader approach like that to improving validation options. This feature may be published soon in a fork. You can ask @iMoses about it. 

Another potential solution is to use something the CUE configuration language: https://cuelang.org/
This also allows adding validation rules to your confirmation. Config files could be written in CUE and then converted to JSON files (if they pass validation) and the JSON files can be read about `node-config`. 

I personally looked at CUE, but it doesn't used a cascading override pattern like `node-config` does, so you have to able and willing to structure your configuration files differently if you depend on multiple stages of override logic.

**Comment by markstos** [comment]
I think node-config already addresses this because of how we tried `undefined` values vs `null` values:

 * Attempting to use `get` a `undefined` value crashes with a related error, so it's a good sentinal value.
 * Attempting to use `get` with a null value just returns `null`: perfect when you really want `null` to be the default value.
