### ISSUE TITLE
[Question] Change default location

### ISSUE THREAD

**Issue by StrangerGithuber** [node-config/node-config#691]
Hello
As I can see the default location is /config folder in the Wiki tutorials.
However if I want to change for example to "includes/configs" folder then how I can do that?
Thanks in advance the answers.

p.s.: I tried with "loadFileConfigs(directory, options)" from https://github.com/node-config/node-config/wiki/Using-Config-Utilities but no effect or maybe I don't understand how to use that module.

**Comment by lorenwest** [comment]
You actually had to delete the following in order to post this:

**Note: for support questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/node-config) and tag your question with `node-config`**. *This repository's issues are reserved for feature requests and bug reports.*

**Comment by markstos** [comment]
This is also documented on the wiki: https://github.com/node-config/node-config/wiki/Environment-Variables#node_config_dir
