### ISSUE TITLE
[BUG] Improve the documentation on Warning "WARNING: NODE_ENV value of 'local' is ambiguous"

### ISSUE THREAD

**Issue by gmuc** [node-config/node-config#719]
**Describe the bug**
If the warning "WARNING: NODE_ENV value of 'local' is ambiguous" apear you write for this in help:
https://github.com/node-config/node-config/wiki/Strict-Mode

This is not very helpful. It describe the problem not the solution. 

Ok if I read your help, I see there is a problem if I use NODE_ENV=local and a config local.json together. But you write not, what is the correct solution if have a local env and set NODE_ENV=local  and I want use a local config. If I understand right, if I want use a production env, I set NODE_ENV=production and write my production config in config/production.json. In this case my production.json overwrite the config values from default.json. Right?

### Please tell us about your environment:

 -  node-config version: 3.3.9
 -  node-version: v18.12.1

**Comment by markstos** [comment]
As mentioned in the docs, `local` is used for "local" overrides. The docs are clear that if you chose `local` for an ENV name, that file will be loaded twice, once because it's the NODE_ENV name and a second time, later in the order as a local override file.

The solution is to not use `local` as a NODE_ENV. Choose laptop or something else instead.

https://github.com/node-config/node-config/wiki/Configuration-Files#file-load-order

 I'm closing this because the docs are in the wiki, which you are welcome to improve.

**Comment by gmuc** [comment]
Thank you for your fast and clear answer. But you have the developer view and all things in the config modul are clear for you. I'm a user and use the config modul only sometimes. Users help some practical hints. For me as user in this case is this extention of your doc helpful:
===
Files named default and local have a special place in the config loading order. Since we also support files simply named after NODE_ENV we can't be sure whether a file named default or local was meant be represent one of these special files, or after your NODE_ENV. Without Strict Mode, these files could end up being loaded twice in the load order which is probably not what you want.

Therefore, please avoid setting NODE_ENV to the value 'local' or 'default'. It is better to use e.g. NODE_ENV=myhost and myhost.json as config. 
===

Ok, this add is on developers view redundant but for me as user it's helpful! Thank you!
