### ISSUE TITLE
Deal With Async Properties in DeferConfig

### ISSUE THREAD

**Issue by akefirad** [node-config/node-config#733]
**Is your feature request related to a problem? Please describe.**
It took me a while to figure it out. Essentially I need to load the secrets from AWS SecretsManager, and then use it in other part of the configuration. For example reading RDS credentials and then use it in another config property (e.g. `database`), something like we do in `deferConfig`.

**Describe the solution you'd like**
This is what I wanted to do:
```ts
import { asyncConfig } from "config/async";

async function loadSecrets(): Promise<{ foo: { bar: string } }> {
  // read the secret from AWS SecretsManager and return the promise!
}

module.exports = {
  secrets: asyncConfig(loadSecrets),
  foo: {
    bar: asyncConfig(function () {
      return this.secrets.then(({ foo }) => foo.bar);
    }),
  },
};
```
If you blindly follow the instruction given for `deferConfig` (given for when the config property is not a promise), and use `deferConfig` for `foo.bar`, you end up with a weird cryptic error (`... Promise.prototype.then ... incompatible target`).

**Describe alternatives you've considered**
It'd be great if `deferConfig` can also deal with promises. If not possible, would be great to add a note to `asyncConfig` (e.g. `asyncConfig` could/should be sued for async properties)

Great work BTW. Thanks.

**Comment by markstos** [comment]
Thanks for the feedback. 

Unless I've missed something, I don't see how `deferConfig()` could work with a promise, because `const config = require('config')` is a sync call. 

I've added a note to the deferConfig page to refer folks to the `asyncConfig` page if they want to resolve promises:

https://github.com/node-config/node-config/wiki/Asynchronous-Configurations
