### ISSUE TITLE
[BUG] custom-environment-variables file does not support cjs extension

### ISSUE THREAD

**Issue by thw0rted** [node-config/node-config#738]
**Describe the bug**
In a `type: 'module'` project, JS-formatted config files must be named `.cjs`, because `.js` files are interpreted as (unsupported) ESM-format.  However, if a user creates a `config/custom-environment-variables.cjs` file, it does not get loaded automatically.  As stated in [the documentation](https://github.com/node-config/node-config/wiki/Environment-Variables#custom-environment-variables), JSON, YAML, `coffee`, or `.js` are supposed to be supported, but this appears to have been an edge-case that was overlooked.  This can be confirmed by logging `config.util.getConfigSources()` at startup.

**Expected behavior**
`custom-environment-variables.cjs` should be considered when looking for custom environment variable files.

### Please tell us about your environment:

 -  node-config version: 3.3.9
 -  node-version: 18.16.0

**Comment by markstos** [comment]
`cjs` support should be there in 3.3.9:

https://github.com/node-config/node-config/commit/8acffa795b139c3fd206334678b54b59e7eab6a7

Also, it looks like the code is there to test all extensions when loading `custom-environment-variables.json.  

Please submit a PR with a failing test that demonstrates the bug-- if the issue is indeed there, a patch is welcome.

**Comment by thw0rted** [comment]
Sorry to trouble you, this wound up being a config issue on my end.
