### ISSUE TITLE
v3.3.10 is a breaking change for webpack, which does not install json5 dep

### ISSUE THREAD

**Issue by shayded-exe** [node-config/node-config#755]
**Describe the bug**
An error is thrown if json5 isn't installed where it wasn't before.

Additionally, this wasn't mentioned in the changelog.

**Expected behavior**
Regular json files are parsed fine if json5 is missing.

### Please tell us about your environment:

 -  node-config version: 3.3.10
 -  node-version: 18.18.2

**Comment by cbazureau** [comment]
Same here !

**Comment by markstos** [comment]
3.3.10 lists `json5` as a dependency. Therefore, `json5` should always be installed. 

How did you manage to install or upgrade  `node-config` 3.3.10 without ending up with the `json5` dependency installed?

**Comment by cbazureau** [comment]
Ok the solution was (i don't know why i forget to do it in this particular build) to exclude node_modules from the bundle (you can use https://www.npmjs.com/package/webpack-node-externals `externals: [nodeExternals()]` for example)

**Comment by jrmyio** [comment]
I am using esbuild to build a project with that uses `config` and ran into `Error: Cannot find module 'json5'` after running the build.

Note that I the build doesn't have a node_modules folder.

**Comment by davo3078** [comment]
> Same problem here.
> 
> I am using esbuild to build a project with that uses `config` and ran into `Error: Cannot find module 'json5'` after running the build.
> 
> The build is supposed to work without a `node_modules `folder.

I have the same problem

**Comment by vitalyster** [comment]
Same issue with `webpack` and `target: 'node'`

**Comment by markstos** [comment]
I'd say this is a webpack issue. Search the issues and PRs for webpack for past and current problems with that environment.

**Comment by markstos** [comment]
Related: 

 * https://github.com/node-config/node-config/issues/681
 * https://github.com/node-config/node-config/pull/358

**Comment by vitalyster** [comment]
@lorenwest Yes, we are using it server-side, `target: node`

**Comment by shayded-exe** [comment]
Regardless, I think `node-config` should be able to work without `json5` and fallback to `JSON.parse` if it doesn't exist.

**Comment by lorenwest** [comment]
We have the choice of reverting the last changes or having someone move this forward to resolve both issues.  @DeutscherDude was the champion of the last changes - would you like to offer an opinion?

**Comment by DeutscherDude** [comment]
Hello There :)
Reverting the changes seems plausible considering the issues it has caused to folks using webpack and other bundlers. 
I am rather certain, that we will go back to having issues with parsing comments though.
The exact problem is already at hand, namely the RegExp that was not properly parsing data from JSON.

Changing it is possible, but will require, in my opinion, a lot of additional testing for all special characters, different alphabets, etc.
I would again be happy to be of aid, but my time this week is rather limited.

**Comment by lorenwest** [comment]
Webpack is a bundler, and I don't know much about it except for seemingly infinite configurability.  Wouldn't a bundler be able to, you know, bundle dependencies?

**Comment by DeutscherDude** [comment]
I had rather little exposure to webpack.
If folks would like to provide some minimal code to reproduce these issue, it would be a great for debugging purposes.

**Comment by lorenwest** [comment]
Surely there are other NPM packages with dependencies (yes, an understatement).  What does webpack do with those?

**Comment by cbazureau** [comment]
For webpack it's simple, as i said earlier, two issues : 

- **Issue 1 :** https://stackoverflow.com/a/42804941 : i can't resolve (during bundling time) syntax like `require(dynamic_var)` . Webpack can resolve simple pattern like ``require(`./locale/${dynamic_var}.json`)`` https://webpack.js.org/guides/dependency-management/#require-with-expression by bundling every file that match the pattern.
- **Issue 2 :** https://github.com/json5/json5/issues/240 : json5 + webpack have issue with default export

So if [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) is not an option for some of you, for me node-config is mainly a node lib (not bundle sized driven) or, if used in browser, it will use json config. So the simple solution can be to hard code json5 require at the top of `parser.js` like this :
 
```
// webpack can't solve dynamic module
// @ref https://webpack.js.org/guides/dependency-management/#require-with-expression
const JSON5Module = require('json5');

// webpack resolves json5 with module field out of the box which lead to this usage
// @ref https://github.com/json5/json5/issues/240
const JSON5 = JSON5Module.default || JSON5Module;
```

At the end 3 kinds of people : 
- Node users that used  [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) => no change for them
- Node users that don't used [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) and use JSON config (if they used something else, like YAML, they already had an issue) => fix the problem
- Browser users => fix the problem (bundling json5 is now required anyway because you choose this lib as the "official parser" for node-config)
